version: "3.9"

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: rag_db
    restart: unless-stopped
    env_file:
      - db.env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./app.db:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag_app
    restart: unless-stopped
    command: npm run dev
    env_file:
      - app.env
    ports:
      - "${APP_PORT:-3000}:3000"
    depends_on:
      - db
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules

  pgadmin:
    image: dpage/pgadmin4
    container_name: rag_pgadmin
    restart: unless-stopped
    env_file:
      - db.env
    ports:
      - "${PGADMIN_PORT:-8080}:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  app_node_modules:
  pgadmin_data:


# webapp: http://localhost:3000
# pgadmin: http://localhost:8080
# database: localhost:5432