services:
  db:
    image: pgvector/pgvector:pg16
    container_name: rag_db
    restart: unless-stopped
    env_file:
      - db.env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag_app
    restart: unless-stopped
    env_file:
      - app.env
    ports:
      - "${APP_PORT:-3000}:3000"
    depends_on:
      - db
      - uploader
    volumes:
      - ./movie_data:/app/movie_data

  uploader:
    build:
      context: ./uploader
      dockerfile: Dockerfile
    container_name: rag_uploader
    restart: unless-stopped
    ports:
      - "${UPLOADER_PORT:-8000}:8000"
    volumes:
      - ./movie_data:/app/movie_data
    environment:
      - CHUNK_API_URL=http://app:3000/api/upload-chunks
      - MOVIE_DATA_DIR=/app/movie_data

  pgadmin:
    image: dpage/pgadmin4
    container_name: rag_pgadmin
    restart: unless-stopped
    env_file:
      - db.env
    ports:
      - "${PGADMIN_PORT:-8080}:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:


# webapp: http://localhost:3000
# pgadmin: http://localhost:8080
# database: localhost:5432
