name: rag-backend
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - fastapi
  - uvicorn
  - libmagic
  - python-magic
  - pip
  - pip:
      - requests
      - unstructured[md,html]
      - markdown
      - beautifulsoup4
      - lxml
      - sentence-transformers
